version: "3.9"
services:
  backend:
    build:
      context: ../
      dockerfile: .devcontainer/backend-devcontainer/Dockerfile
    ports:
      - 4000:4000
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - graphql-study-backend-modules:/workspace/backend/node_modules
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ../
      dockerfile: .devcontainer/frontend-devcontainer/Dockerfile
    ports:
      - 3000:3000
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - graphql-study-frontend-modules:/workspace/frontend/node_modules
    command: /bin/bash
    tty: true
    stdin_open: true
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  graphql-study-backend-modules:
  graphql-study-frontend-modules:
