version: "3.9"
services:
  backend:
    build:
      context: ../
      dockerfile: .devcontainer/backend-devcontainer/Dockerfile
    ports:
      - 4000:4000
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - graphql-study-backend-modules:/workspace/backend/node_modules
    command: /bin/bash
    tty: true
    stdin_open: true

volumes:
  graphql-study-backend-modules:
