version: "3.9"
services:
  application:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 4000:4000
    working_dir: /workspace
    volumes:
      - ../:/workspace
      - app-node-modules:/workspace/node_modules
    command: /bin/bash
    tty: true
    stdin_open: true

volumes:
  app-node-modules:
